### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by EV0LV3** [Markemp/Cryengine-Importer#11]
Getting the error after I try to import files from Hunt with the "Import CryEngine Assets" option:

```
Python: Traceback (most recent call last):
  File "C:\Users\__0x1__\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_cryengine_importer\__init__.py", line 132, in execute
    return Cryengine_Importer.import_asset(context, **keywords)
  File "C:\Users\__0x1__\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 509, in import_asset
    constants.basedir = get_base_dir(path)
  File "C:\Users\__0x1__\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 51, in get_base_dir
    return get_base_dir(os.path.abspath(os.path.join(dirpath, os.pardir)))
  File "C:\Users\__0x1__\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 51, in get_base_dir
    return get_base_dir(os.path.abspath(os.path.join(dirpath, os.pardir)))
  File "C:\Users\__0x1__\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 51, in get_base_dir
    return get_base_dir(os.path.abspath(os.path.join(dirpath, os.pardir)))
  [Previous line repeated 991 more times]
  File "C:\Users\__0x1__\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 48, in get_base_dir
    if os.path.basename(dirpath).lower() == 'objects' or os.path.basename(dirpath).lower() == 'prefabs':
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\ntpath.py", line 214, in basename
    return split(p)[1]
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\ntpath.py", line 184, in split
    seps = _get_bothseps(p)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\ntpath.py", line 35, in _get_bothseps
    if isinstance(path, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object

location: <unknown location>:-1
```

**Comment by Markemp** [comment]
What was the issue?  If it isn't working right I can add it to the backlog.

**Comment by EV0LV3** [comment]
I'm not sure this is a problem off the Cryengine-Importer or the files from the Hunt Showdown.
When I convert the files with Cryengine-Converter I can import the loss .dea files. But when you try to import it with the "Import Cryengine Asset" option. You will get the error like above. 

But not sure if it is the problem of the import or not. So that's the reason why I close it.

**Comment by Markemp** [comment]
Probably an issue with the importer.  I haven't done much with the bulk importer so there's a decent chance that something broke when 2.90 came out.  Reopening; will take a look when I get access to Hunt.

**Comment by EV0LV3** [comment]
If you need any files for research purposes, then I can send them if necessary.

**Comment by Markemp** [comment]
I think I figured out where the bug is in this.  It only works when you select a folder in the `objects` or `prefabs` directory.  It will only convert one directory worth of cryengine files at a time, so you can't start at the root of the game folder and import everything it contains. 

Were you trying to run this outside of those directories?

**Comment by Markemp** [comment]
README.md updated with information about only converting a single directory in the `Objects` or `Prefabs` directory.
