### ISSUE TITLE
Problem importing Mechs Blender 2.92

### ISSUE THREAD

**Issue by vidar7** [Markemp/Cryengine-Importer#12]
Hi, First of all great work there.

looks like you still work on this, cause you released a new io_cryengine_importer.zip on 22-04-2021, 

I got a problem importing mechs, I use win10, blender 2.92 and the newest versions of your tools. I followed you tutorials from mwo Forum and i get this message from Blender:

Python: Traceback (most recent call last):
  File "C:\Users\ograue\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\__init__.py", line 177, in execute
    Cryengine_Importer.import_mech(context, **keywords)
  File "C:\Users\ograue\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 573, in import_mech
    constants.materials = materials.create_materials(matfile, constants.basedir, use_dds, use_tif)
  File "C:\Users\ograue\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\materials.py", line 46, in create_materials
    create_mechcockpit_shader_material(material_xml, material, file_extension)
  File "C:\Users\ograue\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\materials.py", line 147, in create_mechcockpit_shader_material
    texture_node = create_image_texture_node(tree_nodes, texture, file_extension)
  File "C:\Users\ograue\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\materials.py", line 253, in create_image_texture_node
    texture_image = bpy.data.images.load("textures\\default_mat_warning." + file_extension)
RuntimeError: Error: Cannot read 'textures\default_mat_warning..dds': No such file or directory

Sadly it imports only the Bones and not the mech itself, like you do it on your tutorials.

I hope you can fix it, or tell me what im doing wrong.

Again thx for the good work.

Greetings Vidar

**Comment by Markemp** [comment]
Which mech did this happen on?  I'll take a look.

**Comment by vidar7** [comment]
Thx for the fast response,

i tried adder, marauder and gargoyle. blender and this kind of software us new for me, so problem could be there.

**Comment by GregBCOP** [comment]
I'm experiencing a similar chunk definition error but a different error with 2.92 even after a clean install and ensuring that both the converter and importer were up to date. 

Python: Traceback (most recent call last):
  File "C:\Users\Greg\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\__init__.py", line 192, in execute
    Cryengine_Importer.import_mech(context, **keywords)
  File "C:\Users\Greg\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 556, in import_mech
    constants.basedir = get_base_dir(path)
  File "C:\Users\Greg\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 51, in get_base_dir
    return get_base_dir(os.path.abspath(os.path.join(dirpath, os.pardir)))
  File "C:\Users\Greg\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 51, in get_base_dir
    return get_base_dir(os.path.abspath(os.path.join(dirpath, os.pardir)))
  File "C:\Users\Greg\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 51, in get_base_dir
    return get_base_dir(os.path.abspath(os.path.join(dirpath, os.pardir)))
  [Previous line repeated 991 more times]
  File "C:\Users\Greg\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 48, in get_base_dir
    if os.path.basename(dirpath).lower() == 'objects' or os.path.basename(dirpath).lower() == 'prefabs':
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\ntpath.py", line 214, in basename
    return split(p)[1]
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\ntpath.py", line 184, in split
    seps = _get_bothseps(p)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\ntpath.py", line 35, in _get_bothseps
    if isinstance(path, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object

location: <unknown location>:-1

**Comment by Markemp** [comment]
Chunk definition errors shouldn't affect the imports, but I still need to dig into the recursion error.

I did get the adder to work with the current versions though.  @GregBCOP , was the error from the Mech Importer part of the add-on, or Asset Importer?

**Comment by GregBCOP** [comment]
Neither were successful when I tried to import the King Crab.

**Comment by BlackCrusader** [comment]
I tried using an older version (Blender 2.83) and this issue remains.

I tried King Crab and Mad Cat MKII but only the sceletons import

Here is the error message.
![image](https://user-images.githubusercontent.com/85196620/120390632-3cbf1600-c32e-11eb-9cca-89b58cfa9655.png)

**Comment by Markemp** [comment]
The add-on won't work on pre 2.80 versions of Blender.  It only supports the newer versions. 

The runtime error though is what I need.  Going to look at that this weekend.

**Comment by Markemp** [comment]
Figured it out.  Ugh... such a dumb error.

![image](https://user-images.githubusercontent.com/12057128/120945185-f6cacf00-c6ec-11eb-8002-c16a8b3cf0a1.png)

I wish there was a way to do unit testing.  Or even halfway decent integration testing.  New version will come out tonight.  Or soon.

**Comment by Markemp** [comment]
Damn PGI, you make some beautiful mechs.

![image](https://user-images.githubusercontent.com/12057128/120945560-58d80400-c6ee-11eb-9dfe-94428535ee93.png)

**Comment by Markemp** [comment]
v2.0.6 released.  Check out the latest release at https://github.com/Markemp/Cryengine-Importer/releases/latest.  Closing this issue.  If there are other issues, please open a new one.  Thanks everyone!
