### ISSUE TITLE
Import Prefab Error (Blender 2.8.1)

### ISSUE THREAD

**Issue by schmaggis** [Markemp/Cryengine-Importer#7]
Hi There,
I love your tool and just tried to update to version 2.0.0 so I canb use the new Blender 2.8.1. Sadly when testing it with the tutorial Prefab (Mechlab) I got the following Error:

> location: `<unknown location>`:-1
> NameError: name 'import_prefab' is not defined
>     return import_prefab(context, **keywords)
>   File "C:\Users\Schmaggis\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_cryengine_importer\\_\_init__.py", line 253, in execute
> Traceback (most recent call last):

Looks to me that the function "import_prefab" in the file "\__init\__.py" is not found. I looked for it and found it in the file "Cryengine_Importer.py" in the same directory, but I have no idea how to get Blender to find it. :-)

Thanks in advance!! Great work here!
Cheers,
Schmaggis

**Comment by schmaggis** [comment]
Hmm actually I just saw that in the File "\_\_init\_\_.py" is written: 
> \# Cryengine Importer 1.1 (Blender Python module)

Shouldn't it be Version 2.x or something? I had a little success with changing "import_prefab" to "Cryengine_Importer.import_prefab" in line 253 but then had an error in the Cryengine_Importer file:

> 
> Traceback (most recent call last):
>   File "D:\Programmieren\Blender\2.81\2.81\scripts\addons\io_cryengine_importer\__init__.py", line 255, in execute
>     return Cryengine_Importer.import_prefab(context, **keywords)
>   File "D:\Programmieren\Blender\2.81\2.81\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 610, in import_prefab
>     obj = link_geometry(objectname, libraryfile, itemgroupname)
>   File "D:\Programmieren\Blender\2.81\2.81\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 421, in link_geometry
>     data_dest.groups = data_src.groups
> AttributeError: 'bpy_lib' object has no attribute 'groups'
> 
> location: <unknown location>:-1

Is it possible that something with the last build got mixed up between Version 1.1 and Version 2.x? Or is the last Build just not compatible with Blender 2.8.1?

Cheers 
Schmaggis

**Comment by Markemp** [comment]
Unfortunately there are some parts of cryengine importer that I haven't finished converting over to the 2.8 format, and the prefab and asset importers are part of that. :(  I'll try to take a look over the next couple of weeks to get them to support Blender 2.80+.

I'll leave this issue open, as it is valid until it is fixed.

**Comment by Baconator650** [comment]
Don't know if the latest version fixes the the prefab issue:

Python: Traceback (most recent call last):
  File "C:\Users\krazy\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\__init__.py", line 236, in execute
    return Cryengine_Importer.import_prefab(context, **keywords)
  File "C:\Users\krazy\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\Cryengine_Importer.py", line 598, in import_prefab
    prefab = cry_xml.read_file(path)
  File "C:\Users\krazy\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\io_cryengine_importer\CryXmlB\CryXmlReader.py", line 31, in read_file
    c = f.peek(1)[:1].decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 0: unexpected end of data

location: <unknown location>:-1


Would if be possible to add a function or option to replace "missing assets" with a helper/dummy with the pos/rot/scale to be act a as placeholder for users to later replace with the missing asset?

**Comment by MattPlaysSimulations** [comment]
I seem to be having the same issue as Baconator650. I'm using blender V3.1. Any idea how to fix?

**Comment by Markemp** [comment]
I'll take a look at this over the weekend. 👍

**Comment by MattPlaysSimulations** [comment]
Thanks, I got it working as long as I don't use DDS in the settings. (Converting Armoured Warfare). Is there a way for it to import all the parts in the correct location? I'm currently having to position all the parts manually

**Comment by Markemp** [comment]
As long as there is an xml file with the positions of the parts, that should be possible.  

Can you provide more info about which prefab you are using?

**Comment by MattPlaysSimulations** [comment]
I'm trying to import a challenger 2 tank. The converter split it into around 40 different dae parts and when I imported them all, they're all over the place

**Comment by MattPlaysSimulations** [comment]
I'm going to be honest, I have no idea on coding and I'm brand new into blender. I didn't see any prefabs when I extracted them either so I am unsure. How to I convert the textures too? It took me good part of a day using your videos to get the powershell commands to work for me. The textures are showing as "w.dds.0" files and I have no idea how to convert these. Ideally I need to get them into targa format for my purpose. But thanks a lot for investigating and helping me with this!

**Comment by MattPlaysSimulations** [comment]
Hello, any update on getting armoured warfare vehicles compatible with mech importer? thanks
